apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress-test
  namespace: history-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress-ctr
  template:
    metadata:
      labels:
        app: memory-stress-ctr
    spec:
      containers:
      - env:
        - name: RUN_TYPE
          value: memory
        - name: MEMORY_NUM
          value: "950"
        image: beekman9527/cpumemload:latest
        name: memory-stress-ctr
        resources:
          limits:
            memory: 1408Mi
